name: Blog site build

on: 
  pull_request:
    branches: 
      - master
      - Tim
    tags:
      - build

jobs:
  build:
    name: blog build job
    runs-on: ubuntu-latest
  
    steps:
    - name: Refer to repo
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
      
    - name: Into v2
      run: |
        pwd
        cd v2
        pwd
    - name: npm install
      run: |
        pwd
        npm install
    - name: npm build
      run: |
        pwd
        npm run build
