name: Blog site build

on: 
  pull_request:
    branches: 
      - master
      - Tim
    tags:
      - build v*

jobs:
  build:
    name: blog build job
    runs-on: ubuntu-latest
    
    steps:
    - name: Refer to repo
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Into v2
      run: cd v2
    - name: npm install
      run: npm install
    - name: npm build
      run: npm run build
