name: Blog site build

on: 
  pull_request:
    branches: 
      - master
      - Tim
    tags:
      - build

jobs:
  build:
    name: blog build job
    runs-on: macos-latest
  
    steps:
    - name: Refer to repo
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: npm install | build
      run: |
        pwd
        npm ci
        npm run build
      working-directory: ./v2
    - name: Deploy to blog-v2
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.forAction }}
        BRANCH: Tim
        FOLDER: blog-v2

        
        
        
