name: Blog site build

on: 
  pull_request:
    branches: 
      - master
      - Tim
    tags:
      - build

jobs:
  build:
    name: blog build job
    runs-on: ubuntu-latest
  
    steps:
    - name: Refer to repo
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: npm install | build
      run: |
        cd v3
        pwd
        npm install
        npm run:script build
    #- name: list files
    #  run: |
    #    cd v3
     #   pwd
      #  find . -maxdepth 1
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        FOLDER: v2-vue
        
        
        
